/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNITest */

#ifndef _Included_jni_JNITest
#define _Included_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JNITest
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNITest_Hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
